source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'ifanr' do
    pod 'Alamofire'
    pod 'SwiftyJSON'
    pod 'SnapKit'
    pod 'Moya'
    pod 'MonkeyKing', '~> 0.9.2'
    pod 'YYWebImage'
end

#pod 'ShareSDK3'

#pod 'ShareSDK3/ShareSDKUI'
#pod 'MOBFoundation'
#pod 'ShareSDK3/ShareSDKPlatforms/WeChat'