source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'Alamofire'
pod 'SwiftyJSON'
pod 'SnapKit'
pod 'Moya'

pod 'YYWebImage'

pod 'ShareSDK3'

pod 'ShareSDK3/ShareSDKUI'
pod 'MOBFoundation'
pod 'ShareSDK3/ShareSDKPlatforms/WeChat'